services:
  nfq_sylius_omnisend_plugin.command.push_categories:
    class: NFQ\SyliusOmnisendPlugin\Command\CreateBatchCommand
    arguments:
      - '@messenger.routable_message_bus'
    tags:
      - console.command
