services:
  nfq_sylius_omnisend_plugin.message.handler.create_contact:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\CreateContactHandler
    arguments:
      - '@nfq_sylius_omnisend_plugin.manager.contact'
      - '@sylius.repository.customer'
    tags: [messenger.message_handler]

  nfq_sylius_omnisend_plugin.message.handler.update_contact:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\UpdateContactHandler
    arguments:
      - '@nfq_sylius_omnisend_plugin.manager.contact'
      - '@sylius.repository.customer'
    tags: [ messenger.message_handler ]

  nfq_sylius_omnisend_plugin.message.handler.update_category:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\UpdateCategoryHandler
    arguments:
      - '@nfq_sylius_omnisend_plugin.client.omnisend'
      - '@sylius.repository.taxon'
      - '@nfq_sylius_omnisend_plugin.factory.request.category'
    tags: [ messenger.message_handler ]

  nfq_sylius_omnisend_plugin.message.handler.create_category:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\CreateCategoryHandler
    arguments:
      - '@nfq_sylius_omnisend_plugin.client.omnisend'
      - '@sylius.repository.taxon'
      - '@nfq_sylius_omnisend_plugin.factory.request.category'
    tags: [ messenger.message_handler ]

  nfq_sylius_omnisend_plugin.message.handler.delete_category:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\DeleteCategoryHandler
    arguments:
      - '@nfq_sylius_omnisend_plugin.client.omnisend'
      - '@sylius.repository.taxon'
    tags: [ messenger.message_handler ]

  nfq_sylius_omnisend_plugin.message.handler.push_category:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\PushCategoriesHandler
    arguments:
      - '@nfq_sylius_omnisend_plugin.client.omnisend'
      - '@sylius.repository.taxon'
      - '@nfq_sylius_omnisend_plugin.factory.request.category'
      - '@nfq_sylius_omnisend_plugin.factory.request.batch'
    tags: [ messenger.message_handler ]

  nfq_sylius_omnisend_plugin.message.handler.update_cart:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\UpdateCartHandler
    arguments:
      - '@sylius.repository.order'
      - '@nfq_sylius_omnisend_plugin.builder.request.cart_director'
      - '@nfq_sylius_omnisend_plugin.client.omnisend'
    tags: [ messenger.message_handler ]

  nfq_sylius_omnisend_plugin.message.handler.delete_cart:
    class: NFQ\SyliusOmnisendPlugin\Message\Handler\DeleteCartHandler
    arguments:
      - '@sylius.repository.order'
      - '@nfq_sylius_omnisend_plugin.client.omnisend'
    tags: [ messenger.message_handler ]
