services:
  nfq_sylius_omnisend_plugin.resolver.product_image:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ProductImageResolver
    arguments:
      - '@liip_imagine.cache.manager'
      - '%nfq_sylius_omnisend_plugin.product_image.type%'
      - '%nfq_sylius_omnisend_plugin.product_image.filter%'
      - '%nfq_sylius_omnisend_plugin.product_image.default_image%'

  nfq_sylius_omnisend_plugin.resolver.contact_id:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ContactIdResolver
    arguments:
      - '@request_stack'

  nfq_sylius_omnisend_plugin.resolver.order_coupon_context:
    class: NFQ\SyliusOmnisendPlugin\Resolver\OrderCouponResolverContext
    arguments:
      - !tagged 'nfq_sylius_omnisend_plugin.resolver.order_coupon'

  nfq_sylius_omnisend_plugin.resolver.default_order_coupon:
    class: NFQ\SyliusOmnisendPlugin\Resolver\DefaultOrderCouponResolver
    tags:
      - { name: nfq_sylius_omnisend_plugin.resolver.order_coupon, position: -100 }
