services:
  nfq_sylius_omnisend_plugin.resolver.default_product_image:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ProductImageResolver
    arguments:
      - '@liip_imagine.cache.manager'
      - '%nfq_sylius_omnisend_plugin.product_image.type%'
      - '%nfq_sylius_omnisend_plugin.product_image.filter%'
      - '%nfq_sylius_omnisend_plugin.product_image.default_image%'

  nfq_sylius_omnisend_plugin.resolver.contact_id:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ContactIdResolver
    arguments:
      - '@request_stack'

  nfq_sylius_omnisend_plugin.resolver.default_product_additional_data:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ProductAdditionalDataResolver
    arguments:
      - '%nfq_sylius_omnisend_plugin.product_attributes%'

  nfq_sylius_omnisend_plugin.resolver.default_order_coupon:
    class: NFQ\SyliusOmnisendPlugin\Resolver\DefaultOrderCouponResolver

  nfq_sylius_omnisend_plugin.resolver.default_product_url:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ProductUrlResolver
    arguments:
      - '@router'

  nfq_sylius_omnisend_plugin.resolver.default_product_variant_stock:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ProductVariantStockResolver
    arguments:
      - '@sylius.availability_checker.default'
