name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ctype, curl, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, libxml, mbstring, openssl, pcre, phar, simplexml, sodium, spl, tokenizer, xml, xmlwriter

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit